Basic implementation of how stop market orders can be managed in memory.  (#1)
* Basic implentation of the stop order logic.

* Make code more modular.

* Added tests for stoporder.go

* Changed github runner to 1.19 instead of 1.20

* Increased test coverage.

* Cleaned up the code.

* Updated project to include test coverage check.

* Updated to use sed and awk.

* only removed this to test if the coverage runner works as intended.

* Revert "only removed this to test if the coverage runner works as intended."

This reverts commit f0e5494bc24e57dfc07fa802c00ea3d146cdb24e.

* Fixed bumpver.

* Bumped version.

* Updated README.md.

* Removed main.go since not really needed.

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,7 +1,7 @@
 name: Tests
 
 #
-# Run unit tests
+# Run unit tests and fail if coverage is below threshold
 #
 
 on:
@@ -17,19 +17,24 @@ jobs:
     name: >-
      ubuntu-latest
       /
-      1.20
+      1.19
     runs-on: "ubuntu-latest"
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v2
 
       - uses: actions/setup-go@v2
         with:
-          go-version: 1.20
+          go-version: 1.19
 
       - name: Install dependencies
         run: |
           go mod tidy
 
-      - name: Unit tests
+      - name: Run tests and check coverage
         run: |
-          go test ./...
+          go test -v -coverprofile=coverage.out ./...
+          COVERAGE=$(go tool cover -func=coverage.out | sed -n '/total/p' | awk '{print substr($NF, 1, length($NF)-1)}')
+          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
+              echo "Coverage is below 90%: $COVERAGE%"
+              exit 1
+          fi
